# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c810af7ffb30425fd5db8e52c29b2e7e04d6ef6b4a4e739d004393a76e5c36a2c6d15c736bf7b120df49c914318c12f8d878e6e1b52c613a65f924283ee7a22

test:
  secret_key_base: e57fb28037313917c49ad651f4a434e6fc8fc30a044f8fa0e7bf0999f21f8e75c93057353ca00cb56806328fb2a9c03d0e7b8fd9c1fc0db6848f6567524805b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
